export const RENDERER_COMMAND_TYPES = [
  "editCut",
  "editCopy",
  "editPaste",
  "editSelectAll",
  "focusFileSearch",
  "openSelection",
  "editSelection",
  "openLocationSheet",
  "openSettings",
  "zoomIn",
  "zoomOut",
  "resetZoom",
  "openInTerminal",
  "moveSelection",
  "renameSelection",
  "duplicateSelection",
  "newFolder",
  "trashSelection",
  "copySelection",
  "cutSelection",
  "pasteSelection",
  "copyPath",
  "refreshOrApplySearchSort",
  "toggleInfoPanel",
  "toggleInfoRow",
  "goHomeRootTree",
  "rootTreeAtSelection",
  "newTab",
  "reopenClosedTab",
  "closeTab",
  "selectNextTab",
  "selectPreviousTab",
  "openSelectionInNewTab",
  "quickLookSelection",
  "toggleFavorite",
  "showInFinder",
  "showLastSearchResults",
  "viewAsIcons",
  "viewAsList",
  "viewAsDetails",
  "sortByName",
  "sortByModified",
  "sortBySize",
  "sortByKind",
  "toggleFoldersFirst",
  "toggleHiddenFiles",
  "goBack",
  "goForward",
  "goEnclosingFolder",
  "focusTreePane",
  "focusContentPane",
  "openHelp",
  "openKeyboardShortcuts",
] as const;

export type RendererCommandType = (typeof RENDERER_COMMAND_TYPES)[number];

export type RendererCommand = {
  type: RendererCommandType;
};
