export const RENDERER_COMMAND_TYPES = [
  "undo",
  "redo",
  "editCut",
  "editCopy",
  "editPaste",
  "editSelectAll",
  "focusFileSearch",
  "openSelection",
  "editSelection",
  "openLocationSheet",
  "openSettings",
  "zoomIn",
  "zoomOut",
  "resetZoom",
  "openInTerminal",
  "moveSelection",
  "renameSelection",
  "duplicateSelection",
  "newFolder",
  "trashSelection",
  "emptyTrash",
  "ejectVolume",
  "copySelection",
  "cutSelection",
  "pasteSelection",
  "copyPath",
  "showClipboard",
  "clearClipboard",
  "refreshOrApplySearchSort",
  "toggleFolderTree",
  "toggleInfoPanel",
  "toggleInfoRow",
  "customizeToolbar",
  "goHomeRootTree",
  "goDocuments",
  "goDesktop",
  "goDownloads",
  "goLibrary",
  "goMacintoshHD",
  "goApplications",
  "goTrash",
  "rootTreeAtSelection",
  "newWindow",
  "newTab",
  "reopenClosedTab",
  "closeTab",
  "selectNextTab",
  "selectPreviousTab",
  "openSelectionInNewTab",
  "openSelectionInNewWindow",
  "moveTabToNewWindow",
  "mergeAllWindows",
  "quickLookSelection",
  "calculateSize",
  "revealInFolder",
  "toggleFavorite",
  "showInFinder",
  "showLastSearchResults",
  "viewAsIcons",
  "viewAsList",
  "viewAsDetails",
  "sortByName",
  "sortByModified",
  "sortBySize",
  "sortByKind",
  "toggleFoldersFirst",
  "toggleHiddenFiles",
  "goBack",
  "goForward",
  "goEnclosingFolder",
  "focusTreePane",
  "focusContentPane",
  "openHelp",
  "openKeyboardShortcuts",
] as const;

export type RendererCommandType = (typeof RENDERER_COMMAND_TYPES)[number];

const RENDERER_COMMAND_TYPE_SET: ReadonlySet<string> = new Set(RENDERER_COMMAND_TYPES);

export function isRendererCommandType(value: string): value is RendererCommandType {
  return RENDERER_COMMAND_TYPE_SET.has(value);
}

export type RendererCommand = {
  type: RendererCommandType;
};
